services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  shikexi6/marathon-analysis:077f6a8
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64