name: 522_m3
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base>=4.1,<4.2.0
  - r-dplyr=1.1.0
  - r-ggplot2=3.4.0
  - quarto=1.5.57
  - conda-lock=2.5.7       
  - mamba=1.5.11
  - conda=24.11
  - notebook
  - jupyter_core
  - python=3.11